### ISSUE TITLE
request a new release for the project

### ISSUE THREAD

**Issue by chenrui333** [pyenv/pyenv-pip-migrate#8] opened 2021-02-20 18:32 UTC
👋  it has been a while since the last release for the project, raising this issue to create a new release. Thanks!

**Comment by pfheatwole** [comment] 2021-02-21 01:20
Thanks for the heads up, looks like Homebrew is wanting an update too. Closing this as a duplicate of #6

**Closed as completed by pfheatwole** 2021-02-21 01:20 UTC

**Comment by chenrui333** [comment] 2021-02-21 02:02
Thanks @pfheatwole !
